version: '3.8'
services:
  nessus:
    image: tenable/nessus:latest-ubuntu
    restart: always
    container_name: nessus
    volumes:
      - nessus-data:/opt/nessus
    environment:
      TZ: "Asia/Bangkok" 
      USERNAME: '${USERNAME}'
      PASSWORD: '${PASSWORD}'
      ACTIVATION_CODE: '${ACTIVATION_CODE}'
    ports:
      - 8834:8834
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://127.0.0.1:514"
    #    tag: "nessus-va"
networks:
  default:
    name: nessus-net
volumes:
  nessus-data:
